#image: ubuntu:18.04
#
#before_script:
#  - apt-get update -qy
#  - apt-get install -y lftp
#
#build:
#  script:
#    # Sync to FTP
#    - lftp -e "open ftp.stampromo.net; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ /; bye"

services:
  - docker:dind

stages:
  - dependencies
  - test
  - build
  - publish

install_dependencies:
  image: node:14-alpine
  stage: dependencies
  script:
    - npm install
    - npm install --save-dev @angular-devkit/build-angular
  only:
    - master
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

lint:
  image: node:14-alpine
  stage: test
  script:
    - npm link @angular/cli@13.3.0
    - ng lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

build_image:
  image: node:14-alpine
  stage: build
  script:
    - npm link @angular/cli@13.3.0
    - ng build --configuration production
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

push_project:
  image: node:14-alpine
  stage: publish
  only:
    - master
  before_script:
    - apk add lftp
  script:
    - lftp -e "open ftp.stampromo.net; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ /; bye"
