#image: ubuntu:18.04
#
#before_script:
#  - apt-get update -qy
#  - apt-get install -y lftp
#
#build:
#  script:
#    # Sync to FTP
#    - lftp -e "open ftp.stampromo.net; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ /; bye"

services:
  - docker:dind

stages:
  - dependencies
  - test
  - build
  - publish

install_dependencies:
  image: node:19-alpine
  stage: dependencies
  script:
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - package-lock.json
    paths:
        - node_modules

lint:
  image: node:19-alpine
  stage: test
  script:
    - npm link @angular/cli@8.3.21
    - ng lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
        - node_modules
    policy: pull

build_image:
  image: node:19-alpine
  stage: build
  script:
    - npm link @angular/cli@8.3.21
    - npm run build --prod
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
    cache:
      key:
        files:
          - package-lock.json
      paths:
          - node_modules
      policy: pull

push_project:
  image: ubuntu:18.04
  stage: publish
  only:
    - master
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  script:
    - lftp -e "open ftp.stampromo.net; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ /; bye"
